---
apiVersion: v1
kind: Service
metadata:
  name: cicd
  labels:
    app: cicd
  namespace: default
  annotations: {}
spec:
  selector:
    app: cicd
  externalTrafficPolicy: Cluster
  ports:
    - name: cicd-test
      targetPort: 80 # Container port set on the CCE console.
      nodePort: 0
      port: 32001
      protocol: TCP
  type: NodePort
